# -*- mode: ruby -*-
# vi: set ft=ruby :
servers=[
    {
        :hostname => "centos-1",
        :ip => "192.168.100.10",
        :box => "centos/7",
        :ram => 2024,
        :cpu => 3
    },
    {
        :hostname => "centos-2",
        :ip => "192.168.100.11",
        :box => "centos/7",
        :ram => 2024,
        :cpu => 3
    },
    {
        :hostname => "centos-3",
        :ip => "192.168.100.12",
        :box => "centos/7",
        :ram => 2024,
        :cpu => 3
    }
]
Vagrant.configure("2") do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
            # Run Ansible from the Vagrant Host
            #
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "playbook.yml"
            end
        end
    end
end
